# -*- coding: utf-8 -*-
"""DASHBOARD DAILY FILL 0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3d_xnDpdbHImcbkb7idU0flpseeiKBY

### Pertanyaan Bisnis
1. Berapa besar persentase kenaikan rata-rata pengeluaran harian (Amount_IDR) pada akhir pekan (is_weekend) dibandingkan hari kerja selama 3 bulan terakhir, dan apakah anomali ini menyebabkan pelampauan target anggaran harian lebih dari 5 kali dalam sebulan?

2. Seberapa besar deviasi pengeluaran harian (Amount_IDR) terhadap tren mingguan (Amount_IDR_lag_7) pada periode 'High-Spending' (tanggal 25 hingga tanggal 5 bulan berikutnya) di sepanjang tahun 2015-2018, dan apakah lonjakan tersebut mengonsumsi lebih dari 40% total Income bulanan?
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. KONFIGURASI HALAMAN
st.set_page_config(page_title="Personal Finance Dashboard", layout="wide")

# 2. JUDUL DAN DESKRIPSI
st.title("💰 Personal Finance Analysis Dashboard")
st.markdown("""
Dashboard ini dirancang untuk menjawab pertanyaan bisnis terkait pola pengeluaran harian, 
efisiensi budget, dan perbandingan perilaku belanja antara hari kerja vs akhir pekan.
""")

# 3. FUNGSI LOAD DATA
@st.cache_data
def load_data():
    # Ganti sesuai nama file CSV Anda
    file_name = 'Daily Household Transactions.csv'
    try:
        df = pd.read_csv(file_name)
        # 1. Bersihkan nama kolom dari spasi yang tidak sengaja (misal ' Month ' jadi 'Month')
        df.columns = df.columns.str.strip()
        
        # 2. Pastikan Date bertipe datetime
        df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')
        
        # 3. BUAT KOLOM JIKA TIDAK ADA (Ini akan mencegah KeyError)
        if 'Month' not in df.columns:
            df['Month'] = df['Date'].dt.month
            
        if 'Day_of_week' not in df.columns:
            df['Day_of_week'] = df['Date'].dt.day_name()
            
        if 'is_weekend' not in df.columns:
            # 5 = Sabtu, 6 = Minggu
            df['is_weekend'] = df['Date'].dt.weekday.apply(lambda x: 1 if x >= 5 else 0)
            
        # 4. Pastikan kolom lag ada (opsional, untuk mencegah error di chart)
        if 'Amount_IDR_lag_7' not in df.columns:
            df['Amount_IDR_lag_7'] = df['Amount_IDR'].shift(7)

        return df
    except Exception as e:
        st.error(f"Gagal membaca file: {e}")
        return pd.DataFrame() # Kembalikan df kosong jika gagal total

# Panggil datanya
df = load_data()

# Cek apakah datanya kosong sebelum lanjut
if not df.empty:
    # --- SIDEBAR: FILTER ---
    st.sidebar.header("Filter & Target Anggaran")
    
    # Menghapus baris yang Tanggalnya gagal dibaca (NaT)
    df = df.dropna(subset=['Date'])
    
    list_month = sorted(df['Month'].unique().astype(int))
    selected_month = st.sidebar.selectbox("Pilih Bulan (Angka)", options=list_month)
    target_bulanan = st.sidebar.number_input("Target Budget Bulanan (IDR)", value=5000000)

    # ... Lanjutkan dengan kode visualisasi yang sama seperti sebelumnya ...
else:
    st.warning("Data belum berhasil dimuat. Pastikan file CSV tersedia.")
